public enum RuntimeIndexingBatchReason: Sendable, Hashable {
    case appLaunch
    case settingsEnabled
    case manual
    /// Triggered by an entry in `Settings.Indexing.custom.entries`.
    /// `identifier` is the raw user-supplied string (full imagePath or just
    /// the image's last path component); displayed verbatim in the popover.
    case alwaysIndex(identifier: String)

    /// Batches generated by the Heuristic sub-mode (main-executable BFS).
    /// Used by `cancelBatches(matching:)` to scope cancellation when the
    /// user flips the heuristic toggle off while batches are running.
    public var isHeuristic: Bool {
        switch self {
        case .appLaunch, .settingsEnabled: return true
        case .alwaysIndex, .manual: return false
        }
    }

    /// Batches generated by the Custom sub-mode (always-index list).
    public var isCustom: Bool {
        if case .alwaysIndex = self { return true }
        return false
    }

    /// Coarse-grained grouping used by the Background Indexing popover.
    /// Batches sharing a category are displayed under a single collapsible
    /// header (e.g. several `.alwaysIndex(identifier:)` rows collapse into
    /// one "Always Index" group).
    public enum Category: Sendable, Hashable {
        case heuristic
        case alwaysIndex
        case manual
    }

    public var category: Category {
        switch self {
        case .appLaunch, .settingsEnabled: return .heuristic
        case .alwaysIndex: return .alwaysIndex
        case .manual: return .manual
        }
    }
}
