#!/bin/zsh
# Regenerates RuntimePrivateDiscriminatorSourceFiles+KnownFileNames.swift: the names
# of the Swift source files in public repositories whose code ships in Apple's
# frameworks. RuntimePrivateDiscriminatorSourceFiles tries them before it derives
# any name from an image's own names; a name only counts once its MD5 matches a
# discriminator, so a name that is not in the image costs a hash and nothing else.
#
#   RuntimeViewerCore/Scripts/GenerateKnownSwiftSourceFileNames.sh
#
# Needs a signed-in `gh`. Reads from GitHub only; writes nothing but the Swift file.
# Each source is pinned to the commit it resolved to, which the file's header lists.

set -euo pipefail

outputFile="${0:A:h}/../Sources/RuntimeViewerCore/Common/RuntimePrivateDiscriminatorSourceFiles+KnownFileNames.swift"

# repository|ref|directory|what it covers. A ref ending in ^ is that commit's parent.
sources=(
    "OpenSwiftUIProject/OpenSwiftUI|main||SwiftUI and SwiftUICore, whose file names OpenSwiftUI recovered (MIT)"
    "swiftlang/swift-foundation|main||Foundation (Apache 2.0)"
    "swiftlang/swift|main|stdlib/public/|the standard library (Apache 2.0)"
    "swiftlang/swift|da242bd2d4bfbbc1db1742ba58e66f1c168e6f22^|stdlib/public/Darwin/|the Darwin overlays before most moved into the SDK (Apache 2.0)"
    "swiftlang/swift|23c3b15f5f2676dd2cfeaabdaf62ae9b49d6faf1^|stdlib/public/Darwin/|the last Darwin overlays, Foundation's among them (Apache 2.0)"
)

namesFile=$(mktemp)
trap 'rm -f "$namesFile"' EXIT
sourceLines=()

for source in "${sources[@]}"; do
    IFS='|' read -r repository ref directory description <<< "$source"
    if [[ $ref == *^ ]]; then
        commit=$(gh api "repos/$repository/commits/${ref%^}" --jq '.parents[0].sha')
    else
        commit=$(gh api "repos/$repository/commits/$ref" --jq '.sha')
    fi
    if [[ $(gh api "repos/$repository/git/trees/$commit?recursive=1" --jq '.truncated') != false ]]; then
        print -u2 "The tree of $repository at $commit is truncated; list it another way."
        exit 1
    fi
    gh api "repos/$repository/git/trees/$commit?recursive=1" --jq "
        .tree[]
        | select(.type == \"blob\")
        | .path
        | select(startswith(\"$directory\"))
        | select(endswith(\".swift\") or endswith(\".swift.gyb\"))
        | select(test(\"(^|/)(Tests|Benchmarks|Examples?)/\") | not)
    " | sed -e 's#.*/##' -e 's#\.gyb$##' >> "$namesFile"
    sourceLines+=("// - $repository @ $commit${directory:+, $directory}: $description")
    print "$repository @ $commit: $(wc -l < "$namesFile" | tr -d ' ') names so far"
done

names=$(LC_ALL=C sort -u "$namesFile")
if print -r -- "$names" | /usr/bin/grep -q '[\\"]'; then
    print -u2 'A file name contains a backslash or a quotation mark, which the string literal cannot hold as is.'
    exit 1
fi

{
    print -r -- '// Generated by RuntimeViewerCore/Scripts/GenerateKnownSwiftSourceFileNames.sh. Do not edit.'
    print -r -- '//'
    print -r -- '// The names of the Swift source files, tests and benchmarks aside, in:'
    print -rl -- "${sourceLines[@]}"
    print -r -- '//'
    print -r -- '// File names only: nothing else from these repositories is included.'
    print -r -- ''
    print -r -- 'extension RuntimePrivateDiscriminatorSourceFiles {'
    print -r -- "    /// Swift source file names known from public repositories whose code ships in Apple's"
    print -r -- "    /// frameworks, OpenSwiftUI's reconstruction of SwiftUI among them. They are tried first,"
    print -r -- "    /// before any name is derived from an image's own names."
    print -r -- '    public static let knownFileNames: [String] = knownFileNamesText.split(separator: "\n").map(String.init)'
    print -r -- ''
    print -r -- '    private static let knownFileNamesText = """'
    print -r -- "$names" | sed 's/^/    /'
    print -r -- '    """'
    print -r -- '}'
} > "$outputFile"

print "Wrote $(print -r -- "$names" | wc -l | tr -d ' ') names to ${outputFile:A}"
