import Foundation
import MachOKit

struct RuntimeInterfaceExportMetadata: Codable, Sendable {
    struct RuntimeViewerInfo: Codable, Sendable {
        let name: String
        let bundleIdentifier: String
        let version: String
        let build: String
        let gitCommit: String
        let gitBranch: String
        let buildDate: String
    }

    struct ModuleInfo: Codable, Sendable {
        let name: String
        let path: String
        let resolvedPath: String?
        let bundleIdentifier: String?
        let bundleShortVersion: String?
        let bundleVersion: String?
        let installName: String?
        let currentVersion: String?
        let compatibilityVersion: String?
        let sourceVersion: String?
        let uuid: String?
    }

    struct ExportInfo: Codable, Sendable {
        let generatedAt: Date
        let objcFormat: String
        let swiftFormat: String
        let objcInterfaceCount: Int
        let swiftInterfaceCount: Int
        let succeeded: Int
        let failed: Int
    }

    struct LicenseInfo: Codable, Sendable {
        let runtimeViewerLicense: String
        let notice: String
    }

    let runtimeViewer: RuntimeViewerInfo
    let module: ModuleInfo
    let export: ExportInfo
    let license: LicenseInfo

    static func make(
        configuration: RuntimeInterfaceExportConfiguration,
        objcInterfaceCount: Int,
        swiftInterfaceCount: Int,
        succeeded: Int,
        failed: Int,
        generatedAt: Date = Date()
    ) -> RuntimeInterfaceExportMetadata {
        RuntimeInterfaceExportMetadata(
            runtimeViewer: .current,
            module: .resolve(imagePath: configuration.imagePath, imageName: configuration.imageName),
            export: .init(
                generatedAt: generatedAt,
                objcFormat: configuration.objcFormat.displayName,
                swiftFormat: configuration.swiftFormat.displayName,
                objcInterfaceCount: objcInterfaceCount,
                swiftInterfaceCount: swiftInterfaceCount,
                succeeded: succeeded,
                failed: failed
            ),
            license: .standard
        )
    }

    func makeREADME() -> String {
        var lines: [String] = [
            "# RuntimeViewer Export",
            "",
            "Generated by RuntimeViewer \(runtimeViewer.version) (build \(runtimeViewer.build), commit \(runtimeViewer.gitCommit)).",
            "",
            "## RuntimeViewer",
            "",
            "- Name: \(runtimeViewer.name)",
            "- Bundle identifier: \(runtimeViewer.bundleIdentifier)",
            "- Version: \(runtimeViewer.version)",
            "- Build: \(runtimeViewer.build)",
            "- Git commit: \(runtimeViewer.gitCommit)",
            "- Git branch: \(runtimeViewer.gitBranch)",
            "- Build date: \(runtimeViewer.buildDate)",
            "",
            "## Dumped Module",
            "",
            "- Name: \(module.name)",
            "- Path: \(module.path)"
        ]

        if let resolvedPath = module.resolvedPath {
            lines.append("- Resolved path: \(resolvedPath)")
        }
        appendOptional("- Bundle identifier", module.bundleIdentifier, to: &lines)
        appendOptional("- Bundle short version", module.bundleShortVersion, to: &lines)
        appendOptional("- Bundle version", module.bundleVersion, to: &lines)
        appendOptional("- Mach-O install name", module.installName, to: &lines)
        appendOptional("- Mach-O current version", module.currentVersion, to: &lines)
        appendOptional("- Mach-O compatibility version", module.compatibilityVersion, to: &lines)
        appendOptional("- Mach-O source version", module.sourceVersion, to: &lines)
        appendOptional("- Mach-O UUID", module.uuid, to: &lines)

        lines += [
            "",
            "## Export",
            "",
            "- Generated at: \(Self.isoString(from: export.generatedAt))",
            "- ObjC format: \(export.objcFormat)",
            "- Swift format: \(export.swiftFormat)",
            "- ObjC interfaces: \(export.objcInterfaceCount)",
            "- Swift interfaces: \(export.swiftInterfaceCount)",
            "- Succeeded: \(export.succeeded)",
            "- Failed: \(export.failed)",
            "",
            "## License",
            "",
            "- RuntimeViewer license: \(license.runtimeViewerLicense)",
            "- Notice: \(license.notice)",
            ""
        ]

        return lines.joined(separator: "\n")
    }
}

private extension RuntimeInterfaceExportMetadata.RuntimeViewerInfo {
    static var current: Self {
        let info = Bundle.main.infoDictionary ?? [:]
        return .init(
            name: Self.normalized(info["CFBundleName"], fallback: "RuntimeViewer"),
            bundleIdentifier: Self.normalized(info["CFBundleIdentifier"]),
            version: Self.normalized(info["CFBundleShortVersionString"]),
            build: Self.normalized(info["CFBundleVersion"]),
            gitCommit: Self.normalized(info["RuntimeViewerGitCommit"]),
            gitBranch: Self.normalized(info["RuntimeViewerGitBranch"]),
            buildDate: Self.normalized(info["RuntimeViewerBuildDate"])
        )
    }

    static func normalized(_ value: Any?, fallback: String = "unknown") -> String {
        guard let string = value as? String else { return fallback }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !trimmed.hasPrefix("$(") else { return fallback }
        return trimmed
    }
}

private extension RuntimeInterfaceExportMetadata.ModuleInfo {
    struct MachOVersionInfo {
        var installName: String?
        var currentVersion: String?
        var compatibilityVersion: String?
        var sourceVersion: String?
        var uuid: String?
    }

    static func resolve(imagePath: String, imageName: String) -> Self {
        let resolvedPath = DyldUtilities.patchImagePathForDyld(imagePath)
        let displayedResolvedPath = resolvedPath == imagePath ? nil : resolvedPath
        let bundleInfo = bundleInfo(forPath: resolvedPath) ?? bundleInfo(forPath: imagePath)
        let machOInfo = machOVersionInfo(forPath: imagePath, resolvedPath: resolvedPath)

        return .init(
            name: imageName,
            path: imagePath,
            resolvedPath: displayedResolvedPath,
            bundleIdentifier: bundleInfo?["CFBundleIdentifier"],
            bundleShortVersion: bundleInfo?["CFBundleShortVersionString"],
            bundleVersion: bundleInfo?["CFBundleVersion"],
            installName: machOInfo.installName,
            currentVersion: machOInfo.currentVersion,
            compatibilityVersion: machOInfo.compatibilityVersion,
            sourceVersion: machOInfo.sourceVersion,
            uuid: machOInfo.uuid
        )
    }

    static func bundleInfo(forPath path: String) -> [String: String]? {
        let url = URL(fileURLWithPath: path)
        guard let bundleURL = enclosingBundleURL(for: url) else { return nil }

        if let infoDictionary = Bundle(url: bundleURL)?.infoDictionary {
            return stringValues(from: infoDictionary)
        }

        for infoURL in infoPlistCandidates(for: bundleURL) {
            guard let data = try? Data(contentsOf: infoURL),
                  let propertyList = try? PropertyListSerialization.propertyList(from: data, options: [], format: nil),
                  let infoDictionary = propertyList as? [String: Any] else {
                continue
            }
            return stringValues(from: infoDictionary)
        }

        return nil
    }

    static func enclosingBundleURL(for url: URL) -> URL? {
        var current = url
        while current.path != "/" {
            if ["app", "bundle", "framework", "xpc"].contains(current.pathExtension) {
                return current
            }
            let parent = current.deletingLastPathComponent()
            guard parent.path != current.path else { break }
            current = parent
        }
        return nil
    }

    static func infoPlistCandidates(for bundleURL: URL) -> [URL] {
        [
            bundleURL.appendingPathComponent("Info.plist"),
            bundleURL.appendingPathComponent("Resources/Info.plist"),
            bundleURL.appendingPathComponent("Versions/Current/Resources/Info.plist")
        ]
    }

    static func stringValues(from infoDictionary: [String: Any]) -> [String: String] {
        var result: [String: String] = [:]
        for (key, value) in infoDictionary {
            switch value {
            case let string as String:
                result[key] = string
            case let number as NSNumber:
                result[key] = number.stringValue
            default:
                continue
            }
        }
        return result
    }

    static func machOVersionInfo(forPath imagePath: String, resolvedPath: String) -> MachOVersionInfo {
        if let image = DyldUtilities.machOImage(forPath: imagePath) ?? DyldUtilities.machOImage(forPath: resolvedPath) {
            return machOVersionInfo(for: image)
        }

        let url = URL(fileURLWithPath: resolvedPath)
        if FileManager.default.fileExists(atPath: url.path),
           let file = try? MachOFile(url: url) {
            return machOVersionInfo(for: file)
        }

        return MachOVersionInfo()
    }

    static func machOVersionInfo(for image: MachOImage) -> MachOVersionInfo {
        let idDylib = image.loadCommands.info(of: LoadCommand.idDylib)?.dylib(cmdsStart: image.cmdsStartPtr)
        return MachOVersionInfo(
            installName: idDylib?.name,
            currentVersion: idDylib?.currentVersion.description,
            compatibilityVersion: idDylib?.compatibilityVersion.description,
            sourceVersion: image.loadCommands.info(of: LoadCommand.sourceVersion)?.version.description,
            uuid: image.loadCommands.info(of: LoadCommand.uuid)?.uuid.uuidString
        )
    }

    static func machOVersionInfo(for file: MachOFile) -> MachOVersionInfo {
        let idDylib = file.loadCommands.info(of: LoadCommand.idDylib)?.dylib(in: file)
        return MachOVersionInfo(
            installName: idDylib?.name,
            currentVersion: idDylib?.currentVersion.description,
            compatibilityVersion: idDylib?.compatibilityVersion.description,
            sourceVersion: file.loadCommands.info(of: LoadCommand.sourceVersion)?.version.description,
            uuid: file.loadCommands.info(of: LoadCommand.uuid)?.uuid.uuidString
        )
    }
}

private extension RuntimeInterfaceExportMetadata.LicenseInfo {
    static let standard = RuntimeInterfaceExportMetadata.LicenseInfo(
        runtimeViewerLicense: "MIT License",
        notice: "Generated interfaces are derived from the selected module. RuntimeViewer does not grant redistribution rights for the dumped module; review that module's license before sharing exported files."
    )
}

private extension RuntimeInterfaceExportConfiguration.Format {
    var displayName: String {
        switch self {
        case .singleFile:
            return "Single file"
        case .directory:
            return "Directory"
        }
    }
}

private extension RuntimeInterfaceExportMetadata {
    static func isoString(from date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter.string(from: date)
    }

    func appendOptional(_ label: String, _ value: String?, to lines: inout [String]) {
        guard let value, !value.isEmpty else { return }
        lines.append("\(label): \(value)")
    }
}
