import Foundation
import MachOKit

struct RuntimeInterfaceExportMetadata: Codable, Sendable {
    struct RuntimeViewerInfo: Codable, Sendable {
        let name: String
        let bundleIdentifier: String
        let version: String
        let build: String
        let gitCommit: String
        let gitBranch: String
        let buildDate: String
    }

    struct ModuleInfo: Codable, Sendable {
        let name: String
        let path: String
        let resolvedPath: String?
        let bundleIdentifier: String?
        let bundleShortVersion: String?
        let bundleVersion: String?
        let installName: String?
        let currentVersion: String?
        let compatibilityVersion: String?
        let sourceVersion: String?
        let uuid: String?
    }

    struct ExportInfo: Codable, Sendable {
        let generatedAt: Date
        let objcFormat: String
        let swiftFormat: String
        let objcInterfaceCount: Int
        let swiftInterfaceCount: Int
        let succeeded: Int
        let failed: Int
        let dumpOptions: DumpOptionsInfo
    }

    struct DumpOptionsInfo: Codable, Sendable {
        let objcHeaderOptions: [DumpOptionInfo]
        let swiftInterfaceOptions: [DumpOptionInfo]
        let transformerOptions: [DumpOptionInfo]
    }

    struct DumpOptionInfo: Codable, Sendable {
        let name: String
        let value: String
        let description: String
    }

    struct LicenseInfo: Codable, Sendable {
        let runtimeViewerLicense: String
        let notice: String
    }

    let runtimeViewer: RuntimeViewerInfo
    let module: ModuleInfo
    let export: ExportInfo
    let license: LicenseInfo

    static func make(
        configuration: RuntimeInterfaceExportConfiguration,
        module: ModuleInfo? = nil,
        objcInterfaceCount: Int,
        swiftInterfaceCount: Int,
        succeeded: Int,
        failed: Int,
        generatedAt: Date = Date()
    ) -> RuntimeInterfaceExportMetadata {
        RuntimeInterfaceExportMetadata(
            runtimeViewer: .current,
            module: module ?? .resolve(imagePath: configuration.imagePath, imageName: configuration.imageName),
            export: .init(
                generatedAt: generatedAt,
                objcFormat: configuration.objcFormat.displayName,
                swiftFormat: configuration.swiftFormat.displayName,
                objcInterfaceCount: objcInterfaceCount,
                swiftInterfaceCount: swiftInterfaceCount,
                succeeded: succeeded,
                failed: failed,
                dumpOptions: .describe(configuration.generationOptions)
            ),
            license: .standard
        )
    }

    func makeREADME() -> String {
        var lines: [String] = [
            "# RuntimeViewer Export",
            "",
            "Generated by RuntimeViewer \(runtimeViewer.version) (build \(runtimeViewer.build), commit \(runtimeViewer.gitCommit)).",
            "",
            "## RuntimeViewer",
            "",
            "- Name: \(runtimeViewer.name)",
            "- Bundle identifier: \(runtimeViewer.bundleIdentifier)",
            "- Version: \(runtimeViewer.version)",
            "- Build: \(runtimeViewer.build)",
            "- Git commit: \(runtimeViewer.gitCommit)",
            "- Git branch: \(runtimeViewer.gitBranch)",
            "- Build date: \(runtimeViewer.buildDate)",
            "",
            "## Dumped Module",
            "",
            "- Name: \(module.name)",
            "- Path: \(module.path)"
        ]

        if let resolvedPath = module.resolvedPath {
            lines.append("- Resolved path: \(resolvedPath)")
        }
        appendOptional("- Bundle identifier", module.bundleIdentifier, to: &lines)
        appendOptional("- Bundle short version", module.bundleShortVersion, to: &lines)
        appendOptional("- Bundle version", module.bundleVersion, to: &lines)
        appendOptional("- Mach-O install name", module.installName, to: &lines)
        appendOptional("- Mach-O current version", module.currentVersion, to: &lines)
        appendOptional("- Mach-O compatibility version", module.compatibilityVersion, to: &lines)
        appendOptional("- Mach-O source version", module.sourceVersion, to: &lines)
        appendOptional("- Mach-O UUID", module.uuid, to: &lines)

        lines += [
            "",
            "## Export",
            "",
            "- Generated at: \(Self.isoString(from: export.generatedAt))",
            "- ObjC format: \(export.objcFormat)",
            "- Swift format: \(export.swiftFormat)",
            "- ObjC interfaces: \(export.objcInterfaceCount)",
            "- Swift interfaces: \(export.swiftInterfaceCount)",
            "- Succeeded: \(export.succeeded)",
            "- Failed: \(export.failed)"
        ]

        lines += [
            "",
            "## Dump Options"
        ]

        appendOptionSection("Objective-C Header Options", export.dumpOptions.objcHeaderOptions, to: &lines)
        appendOptionSection("Swift Interface Options", export.dumpOptions.swiftInterfaceOptions, to: &lines)
        appendOptionSection("Transformer Options", export.dumpOptions.transformerOptions, to: &lines)

        lines += [
            "## License",
            "",
            "- RuntimeViewer license: \(license.runtimeViewerLicense)",
            "- Notice: \(license.notice)",
            ""
        ]

        return lines.joined(separator: "\n")
    }
}

extension RuntimeInterfaceExportMetadata.DumpOptionsInfo {
    static func describe(_ options: RuntimeObjectInterface.GenerationOptions) -> Self {
        .init(
            objcHeaderOptions: describe(options.objcHeaderOptions),
            swiftInterfaceOptions: describe(options.swiftInterfaceOptions),
            transformerOptions: describe(options.transformer)
        )
    }

    private static func describe(_ options: ObjCGenerationOptions) -> [RuntimeInterfaceExportMetadata.DumpOptionInfo] {
        [
            option(
                "Strip protocol conformance",
                options.stripProtocolConformance,
                "Omits protocol conformance lists from generated Objective-C declarations."
            ),
            option(
                "Strip overrides",
                options.stripOverrides,
                "Omits method override markers from generated Objective-C declarations."
            ),
            option(
                "Strip synthesized ivars",
                options.stripSynthesizedIvars,
                "Omits synthesized ivars from generated Objective-C output."
            ),
            option(
                "Strip synthesized methods",
                options.stripSynthesizedMethods,
                "Omits synthesized methods from generated Objective-C output."
            ),
            option(
                "Strip constructor methods",
                options.stripCtorMethod,
                "Omits constructor methods from generated Objective-C output."
            ),
            option(
                "Strip destructor methods",
                options.stripDtorMethod,
                "Omits destructor methods from generated Objective-C output."
            ),
            option(
                "Add ivar offset comments",
                options.addIvarOffsetComments,
                "Adds ivar memory offset comments to generated Objective-C ivar declarations."
            ),
            option(
                "Add property attributes comments",
                options.addPropertyAttributesComments,
                "Adds property attribute comments to generated Objective-C properties."
            ),
            option(
                "Add method IMP address comments",
                options.addMethodIMPAddressComments,
                "Adds implementation address comments to generated Objective-C methods."
            ),
            option(
                "Add property accessor address comments",
                options.addPropertyAccessorAddressComments,
                "Adds getter and setter implementation address comments to generated Objective-C properties."
            )
        ]
    }

    private static func describe(_ options: SwiftGenerationOptions) -> [RuntimeInterfaceExportMetadata.DumpOptionInfo] {
        [
            option(
                "Print stripped symbolic items",
                options.printStrippedSymbolicItem,
                "Prints symbolic Swift items that were stripped or could not be fully recovered."
            ),
            option(
                "Print field offsets",
                options.printFieldOffset,
                "Adds stored-property field offset comments to generated Swift interfaces."
            ),
            option(
                "Print expanded field offsets",
                options.printExpandedFieldOffset,
                "Adds expanded field offset information when the Swift metadata exposes it."
            ),
            option(
                "Print vtable offsets",
                options.printVTableOffset,
                "Adds virtual table slot offset comments to generated Swift interfaces."
            ),
            option(
                "Print protocol witness table offsets",
                options.printPWTOffset,
                "Adds protocol witness table offset comments to generated Swift interfaces."
            ),
            option(
                "Print member addresses",
                options.printMemberAddress,
                "Adds member address comments to generated Swift declarations."
            ),
            option(
                "Print type layouts",
                options.printTypeLayout,
                "Adds type size, stride, alignment, and layout comments to generated Swift interfaces."
            ),
            option(
                "Print enum layouts",
                options.printEnumLayout,
                "Adds enum payload and tag layout comments to generated Swift interfaces."
            ),
            option(
                "Synthesize opaque types",
                options.synthesizeOpaqueType,
                "Synthesizes placeholder declarations for opaque Swift types when needed."
            ),
            .init(
                name: "Member sort order",
                value: options.memberSortOrder.displayName,
                description: "Controls how members are ordered in generated Swift interfaces."
            )
        ]
    }

    private static func describe(_ configuration: Transformer.Configuration) -> [RuntimeInterfaceExportMetadata.DumpOptionInfo] {
        [
            .init(
                name: Transformer.CType.displayName,
                value: moduleValue(
                    isEnabled: configuration.objc.cType.isEnabled,
                    details: ["replacements: \(replacementSummary(configuration.objc.cType.replacements))"]
                ),
                description: "Rewrites matching C primitive type spellings in Objective-C output."
            ),
            .init(
                name: Transformer.ObjCIvarOffset.displayName,
                value: moduleValue(
                    isEnabled: configuration.objc.ivarOffset.isEnabled,
                    details: [
                        "template: `\(configuration.objc.ivarOffset.template)`",
                        "number format: \(numberFormat(usesHexadecimal: configuration.objc.ivarOffset.useHexadecimal))"
                    ]
                ),
                description: "Controls the text format for Objective-C ivar offset comments."
            ),
            .init(
                name: Transformer.SwiftFieldOffset.displayName,
                value: moduleValue(
                    isEnabled: configuration.swift.swiftFieldOffset.isEnabled,
                    details: [
                        "template: `\(configuration.swift.swiftFieldOffset.template)`",
                        "number format: \(numberFormat(usesHexadecimal: configuration.swift.swiftFieldOffset.useHexadecimal))"
                    ]
                ),
                description: "Controls the text format for Swift field offset comments."
            ),
            .init(
                name: Transformer.SwiftVTableOffset.displayName,
                value: moduleValue(
                    isEnabled: configuration.swift.swiftVTableOffset.isEnabled,
                    details: [
                        "template: `\(configuration.swift.swiftVTableOffset.template)`",
                        "labeled template: `\(configuration.swift.swiftVTableOffset.labeledTemplate)`",
                        "number format: \(numberFormat(usesHexadecimal: configuration.swift.swiftVTableOffset.useHexadecimal))"
                    ]
                ),
                description: "Controls the text format for Swift virtual table offset comments."
            ),
            .init(
                name: Transformer.SwiftMemberAddress.displayName,
                value: moduleValue(
                    isEnabled: configuration.swift.swiftMemberAddress.isEnabled,
                    details: [
                        "template: `\(configuration.swift.swiftMemberAddress.template)`",
                        "number format: \(numberFormat(usesHexadecimal: configuration.swift.swiftMemberAddress.useHexadecimal))"
                    ]
                ),
                description: "Controls the text format for Swift member address comments."
            ),
            .init(
                name: Transformer.SwiftTypeLayout.displayName,
                value: moduleValue(
                    isEnabled: configuration.swift.swiftTypeLayout.isEnabled,
                    details: [
                        "template: `\(configuration.swift.swiftTypeLayout.template)`",
                        "number format: \(numberFormat(usesHexadecimal: configuration.swift.swiftTypeLayout.useHexadecimal))"
                    ]
                ),
                description: "Controls the text format for Swift type layout comments."
            ),
            .init(
                name: Transformer.SwiftEnumLayout.displayName,
                value: moduleValue(
                    isEnabled: configuration.swift.swiftEnumLayout.isEnabled,
                    details: [
                        "template: `\(configuration.swift.swiftEnumLayout.template)`",
                        "case template: `\(configuration.swift.swiftEnumLayout.caseTemplate)`",
                        "memory offset template: `\(configuration.swift.swiftEnumLayout.memoryOffsetTemplate)`",
                        "number format: \(numberFormat(usesHexadecimal: configuration.swift.swiftEnumLayout.useHexadecimal))"
                    ]
                ),
                description: "Controls the text format for Swift enum layout comments."
            )
        ]
    }

    private static func option(
        _ name: String,
        _ isEnabled: Bool,
        _ description: String
    ) -> RuntimeInterfaceExportMetadata.DumpOptionInfo {
        .init(name: name, value: enabledText(isEnabled), description: description)
    }

    private static func enabledText(_ isEnabled: Bool) -> String {
        isEnabled ? "Enabled" : "Disabled"
    }

    private static func moduleValue(isEnabled: Bool, details: [String]) -> String {
        ([enabledText(isEnabled)] + details).joined(separator: "; ")
    }

    private static func numberFormat(usesHexadecimal: Bool) -> String {
        usesHexadecimal ? "hexadecimal" : "decimal"
    }

    private static func replacementSummary(_ replacements: [Transformer.CType.Pattern: String]) -> String {
        let activeReplacements = replacements
            .filter { !$0.value.isEmpty }
            .sorted { $0.key.displayName < $1.key.displayName }

        guard !activeReplacements.isEmpty else { return "none" }

        return activeReplacements
            .map { "`\($0.key.displayName) -> \($0.value)`" }
            .joined(separator: ", ")
    }
}

private extension RuntimeInterfaceExportMetadata.RuntimeViewerInfo {
    static var current: Self {
        let info = Bundle.main.infoDictionary ?? [:]
        return .init(
            name: Self.normalized(info["CFBundleName"], fallback: "RuntimeViewer"),
            bundleIdentifier: Self.normalized(info["CFBundleIdentifier"]),
            version: Self.normalized(info["CFBundleShortVersionString"]),
            build: Self.normalized(info["CFBundleVersion"]),
            gitCommit: Self.normalized(info["RuntimeViewerGitCommit"]),
            gitBranch: Self.normalized(info["RuntimeViewerGitBranch"]),
            buildDate: Self.normalized(info["RuntimeViewerBuildDate"])
        )
    }

    static func normalized(_ value: Any?, fallback: String = "unknown") -> String {
        guard let string = value as? String else { return fallback }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !trimmed.hasPrefix("$(") else { return fallback }
        return trimmed
    }
}

extension RuntimeInterfaceExportMetadata.ModuleInfo {
    static func resolve(imagePath: String, imageName: String) -> Self {
        let resolvedPath = DyldUtilities.patchImagePathForDyld(imagePath)
        let displayedResolvedPath = resolvedPath == imagePath ? nil : resolvedPath
        let bundleInfo = bundleInfo(forPath: resolvedPath) ?? bundleInfo(forPath: imagePath)
        let machOInfo = machOVersionInfo(forPath: imagePath, resolvedPath: resolvedPath)

        return .init(
            name: imageName,
            path: imagePath,
            resolvedPath: displayedResolvedPath,
            bundleIdentifier: bundleInfo?["CFBundleIdentifier"],
            bundleShortVersion: bundleInfo?["CFBundleShortVersionString"],
            bundleVersion: bundleInfo?["CFBundleVersion"],
            installName: machOInfo.installName,
            currentVersion: machOInfo.currentVersion,
            compatibilityVersion: machOInfo.compatibilityVersion,
            sourceVersion: machOInfo.sourceVersion,
            uuid: machOInfo.uuid
        )
    }
}

private extension RuntimeInterfaceExportMetadata.ModuleInfo {
    struct MachOVersionInfo {
        var installName: String?
        var currentVersion: String?
        var compatibilityVersion: String?
        var sourceVersion: String?
        var uuid: String?
    }

    static func bundleInfo(forPath path: String) -> [String: String]? {
        let url = URL(fileURLWithPath: path)
        guard let bundleURL = enclosingBundleURL(for: url) else { return nil }

        if let infoDictionary = Bundle(url: bundleURL)?.infoDictionary {
            return stringValues(from: infoDictionary)
        }

        for infoURL in infoPlistCandidates(for: bundleURL) {
            guard let data = try? Data(contentsOf: infoURL),
                  let propertyList = try? PropertyListSerialization.propertyList(from: data, options: [], format: nil),
                  let infoDictionary = propertyList as? [String: Any] else {
                continue
            }
            return stringValues(from: infoDictionary)
        }

        return nil
    }

    static func enclosingBundleURL(for url: URL) -> URL? {
        var current = url
        while current.path != "/" {
            if ["app", "bundle", "framework", "xpc"].contains(current.pathExtension) {
                return current
            }
            let parent = current.deletingLastPathComponent()
            guard parent.path != current.path else { break }
            current = parent
        }
        return nil
    }

    static func infoPlistCandidates(for bundleURL: URL) -> [URL] {
        [
            bundleURL.appendingPathComponent("Info.plist"),
            bundleURL.appendingPathComponent("Resources/Info.plist"),
            bundleURL.appendingPathComponent("Versions/Current/Resources/Info.plist")
        ]
    }

    static func stringValues(from infoDictionary: [String: Any]) -> [String: String] {
        var result: [String: String] = [:]
        for (key, value) in infoDictionary {
            switch value {
            case let string as String:
                result[key] = string
            case let number as NSNumber:
                result[key] = number.stringValue
            default:
                continue
            }
        }
        return result
    }

    static func machOVersionInfo(forPath imagePath: String, resolvedPath: String) -> MachOVersionInfo {
        if let image = DyldUtilities.exactMachOImage(forPath: imagePath) ?? DyldUtilities.exactMachOImage(forPath: resolvedPath) {
            return machOVersionInfo(for: image)
        }

        let url = URL(fileURLWithPath: resolvedPath)
        if FileManager.default.fileExists(atPath: url.path),
           let file = try? MachOFile(url: url) {
            return machOVersionInfo(for: file)
        }

        return MachOVersionInfo()
    }

    static func machOVersionInfo(for image: MachOImage) -> MachOVersionInfo {
        let idDylib = image.loadCommands.info(of: LoadCommand.idDylib)?.dylib(cmdsStart: image.cmdsStartPtr)
        return MachOVersionInfo(
            installName: idDylib?.name,
            currentVersion: idDylib?.currentVersion.description,
            compatibilityVersion: idDylib?.compatibilityVersion.description,
            sourceVersion: image.loadCommands.info(of: LoadCommand.sourceVersion)?.version.description,
            uuid: image.loadCommands.info(of: LoadCommand.uuid)?.uuid.uuidString
        )
    }

    static func machOVersionInfo(for file: MachOFile) -> MachOVersionInfo {
        let idDylib = file.loadCommands.info(of: LoadCommand.idDylib)?.dylib(in: file)
        return MachOVersionInfo(
            installName: idDylib?.name,
            currentVersion: idDylib?.currentVersion.description,
            compatibilityVersion: idDylib?.compatibilityVersion.description,
            sourceVersion: file.loadCommands.info(of: LoadCommand.sourceVersion)?.version.description,
            uuid: file.loadCommands.info(of: LoadCommand.uuid)?.uuid.uuidString
        )
    }
}

private extension RuntimeInterfaceExportMetadata.LicenseInfo {
    static let standard = RuntimeInterfaceExportMetadata.LicenseInfo(
        runtimeViewerLicense: "MIT License",
        notice: "Generated interfaces are derived from the selected module. RuntimeViewer does not grant redistribution rights for the dumped module; review that module's license before sharing exported files."
    )
}

private extension RuntimeInterfaceExportConfiguration.Format {
    var displayName: String {
        switch self {
        case .singleFile:
            return "Single file"
        case .directory:
            return "Directory"
        }
    }
}

private extension SwiftGenerationOptions.MemberSortOrder {
    var displayName: String {
        switch self {
        case .byCategory:
            return "By category"
        case .byOffset:
            return "By offset"
        }
    }
}

private extension RuntimeInterfaceExportMetadata {
    static func isoString(from date: Date) -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter.string(from: date)
    }

    func appendOptional(_ label: String, _ value: String?, to lines: inout [String]) {
        guard let value, !value.isEmpty else { return }
        lines.append("\(label): \(value)")
    }

    func appendOptionSection(
        _ title: String,
        _ options: [DumpOptionInfo],
        to lines: inout [String]
    ) {
        lines += [
            "",
            "### \(title)",
            ""
        ]

        for option in options {
            lines.append("- \(option.name): \(option.value) - \(option.description)")
        }
    }
}
